# https://docs.readthedocs.io/en/stable/config-file/v2.html
---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - pip install --user hererocks
    - hererocks lua51 -l5.1 -rlatest
    - source lua51/bin/activate
    - luarocks install --local ldoc lua-discount
    - ldoc .
    - mv doc $READTHEDOCS_OUTPUT/html
