# https://docs.readthedocs.io/en/stable/config-file/v2.html
---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - luarocks install --local ldoc lua-discount
    - ldoc .
    - mv doc $READTHEDOCS_OUTPUT/html
